---
#
# start of phase I - detect all cyclic paths
#
- name: "cyclic paths"
  platform42.neo4j.query:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    query: |
      MATCH p=(account:Account)-[:TRANSACTION*2..6]->(account)
      RETURN
        account.entity_name AS startAccount,
        [x IN nodes(p) | x.entity_name] AS cyclePath,
        length(p) AS hops,
        reduce(total = 0, t IN relationships(p) | total + t.amount) AS totalAmount
      ORDER BY totalAmount DESC;
  register: cycle_paths

- name: "create next path iterator"
  ansible.builtin.set_fact:
    cycle_paths_phase_1: "{{ cycle_paths.query.cypher_response }}"


